name: todo_list
description: A simple to-do list app using Flutter.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2 # Downgraded to 6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
